### ISSUE TITLE
Integrate with traffic

### ISSUE THREAD

**Issue by aeroevan** [DGAC/Acropole#5]
It would be nice to either accept traffic Flight objects as input and/or monkeypatch in a method on traffic.core.Flight to provide an alternative to the current fuelflow() method

**Comment by JarryGabriel** [comment]
Hi, sorry for the late answer, thanks for your feedback. I will look at that :) !

**Comment by JarryGabriel** [comment]
Ok so if you have a traffic flight you can use directly Acropole by passing flight.data (which return a dataframe) instead of flight. Thx @junzis for the fast answer ;)
